# Generated by Django 4.2.4 on 2023-08-25 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('form_submitted', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=50, null=True)),
                ('user_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyUserForm3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_signer', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian')], max_length=100)),
                ('cosigner_aadhar', models.FileField(upload_to='')),
                ('cosigner_pan', models.FileField(upload_to='')),
                ('cosigner_address', models.FileField(upload_to='')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User_main3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyUserForm2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_choices', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=50)),
                ('class_10th_score', models.IntegerField()),
                ('class_12th_score', models.IntegerField()),
                ('graduation_score', models.IntegerField()),
                ('cat_score', models.CharField(max_length=50)),
                ('offer_letter_qs', models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('not yet', 'not yet')], max_length=50)),
                ('offer_letter', models.FileField(upload_to='')),
                ('aadhar_card', models.FileField(upload_to='')),
                ('pan_card', models.FileField(upload_to='')),
                ('address_proof', models.FileField(upload_to='')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User_main2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyUserForm1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField()),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('currently_working', models.CharField(choices=[('A Student', 'A Student'), ('A Working employee', 'A working employee'), ('On Break', 'On Break')], max_length=50)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User_main1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyUserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_no', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('currently_working', models.CharField(blank=True, choices=[('A Student', 'A Student'), ('A Working employee', 'A working employee'), ('On Break', 'On Break')], max_length=50, null=True)),
                ('cat_choices', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=50, null=True)),
                ('class_10th_score', models.IntegerField(blank=True, null=True)),
                ('class_12th_score', models.IntegerField(blank=True, null=True)),
                ('graduation_score', models.IntegerField(blank=True, null=True)),
                ('cat_score', models.CharField(blank=True, max_length=50, null=True)),
                ('offer_letter_qs', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('not yet', 'not yet')], max_length=50, null=True)),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='')),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to='')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='')),
                ('address_proof', models.FileField(blank=True, null=True, upload_to='')),
                ('co_signer', models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian')], max_length=100, null=True)),
                ('cosigner_aadhar', models.FileField(blank=True, null=True, upload_to='')),
                ('cosigner_pan', models.FileField(blank=True, null=True, upload_to='')),
                ('cosigner_address', models.FileField(blank=True, null=True, upload_to='')),
                ('user_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_main', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
