# Generated by Django 4.2.4 on 2023-08-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUserForm',
        ),
    ]
