# Generated by Django 4.2.4 on 2023-08-25 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_delete_myuserform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuserform1',
            name='user_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_main1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myuserform2',
            name='user_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_main2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myuserform3',
            name='user_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_main3', to=settings.AUTH_USER_MODEL),
        ),
    ]
