# Generated by Django 4.2.4 on 2023-08-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_myuserform1_user_id_alter_myuserform2_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='form_submitted',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=50, null=True),
        ),
    ]
